INSERT INTO equipo (nombre, apellidos, descripcion, linkedin, github)
VALUES
('Laura', 'Higuera Romero', 'Desarrolladora full-stack con estudios también del grado de Publicidad y Relaciones Públicas. Proyectos realizados con los lenguajes Java, SQL , noSQL y JavaScript usando las librerías node y react en este último. Pasión por el backend , las bases de datos y la lógica de la programación.', 'https://www.linkedin.com/in/laura-higuera-romero', 'https://github.com/laurahigueraromero'),
('Pablo', 'Herrero González-Barros', 'Soy un Técnico Superior en Desarrollo de Aplicaciones Web, con un máster de formación no reglada en Desarrollo Web y alto nivel de inglés. También he trabajado con distintas herramientas de administración. Me apasiona todo lo que tenga que ver con la tecnología y busco formas de aprender más cada día y aplicarlo a proyectos personales que tengo en curso.', 'https://www.linkedin.com/in/pablo-herrero-gonzalez/', 'https://github.com/pablohgb'),
('Javier', 'Monzón Rosique', 'Soy un estudiante de Grado Superior en Desarrollo de Aplicaciones Web y Grado en Sistemas Microinformáticos y Redes. Me encanta todo lo relacionado con la tecnología y en especial con la programación, busco formas de aprender cada día para aplicarlo en mis proyectos personales.', 'https://www.linkedin.com/in/javiermonzonros/', 'https://github.com/JotaMoncho'),
('Sofía', 'Lacal Rodríguez', 'Estudiante de Desarrollo de Aplicaciones Web con alto nivel de inglés, entusiasta de la tecnología y con conocimiento de diferentes lenguajes de programación. Con experiencia laboral como enfermera de quirófano. Me encanta trabajar en equipo y buscar soluciones innovadoras. Tengo gran motivación por ampliar mis conocimientos tecnológicas y lenguajes, con el fin de seguir creciendo profesionalmente.', NULL, 'https://github.com/SofiaLacal');



